package errors

const (
	ErrCodeInvalidCredential        = "INVALID_CREDENTIALS"
	ErrCodeInvalidAPIKey            = "INVALID_API_KEY"
	ErrCodeAPIValidation            = "API_VALIDATION_ERROR"
	ErrCodeRequestForbidden         = "REQUEST_FORBIDDEN_ERROR"
	ErrCodeFeatureNotActivated      = "FEATURE_NOT_ACTIVATED"
	ErrCodeFeatureNotSupported      = "FEATURE_NOT_SUPPORTED"
	ErrCodeNotFound                 = "NOT_FOUND"
	ErrCodeResourceNotFound         = "RESOURCE_NOT_FOUND"
	ErrCodeResourceNotComplete      = "RESOURCE_NOT_COMPLETE"
	ErrCodeDuplicate                = "DUPLICATE_ERROR"
	ErrCodeIdempotency              = "IDEMPOTENCY_ERROR"
	ErrCodeFrequencyAboveLimit      = "FREQUENCY_ABOVE_LIMIT"
	ErrCodeDatabase                 = "DATABASE_ERROR"
	ErrCodeInternal                 = "INTERNAL_ERROR"
	ErrCodeBadGateway               = "BAD_GATEWAY"
	ErrCodeServiceUnavailable       = "SERVICE_UNAVAILABLE"
	ErrCodeGatewayTimeout           = "GATEWAY_TIMEOUT"
	ErrCodeChannelNotActivated      = "CHANNEL_NOT_ACTIVATED"
	ErrCodeChannelUnavailable       = "CHANNEL_UNAVAILABLE"
	ErrCodeMaxAmountLimit           = "MAX_AMOUNT_LIMIT_ERROR"
	ErrCodePartnerChannel           = "PARTNER_CHANNEL_ERROR"
	ErrCodeInvalidAccountDetails    = "INVALID_ACCOUNT_DETAILS"
	ErrCodeInvalidPaymentMethod     = "INVALID_PAYMENT_METHOD"
	ErrCodePaymentRejectedByChannel = "PAYMENT_REJECTED_BY_CHANNEL"
	ErrCodePaymentExpired           = "PAYMENT_EXPIRED"
	ErrCodePaymentCancelled         = "PAYMENT_CANCELLED"
	ErrCodeInsufficientBalance      = "INSUFFICIENT_BALANCE"
	ErrCodeInvalidAmount            = "INVALID_AMOUNT"
	ErrCodeInvalidRequest           = "INVALID_REQUEST"
	ErrCodeTransactionInProgress    = "TRANSACTION_IN_PROGRESS"
	ErrCodeNotPermitted             = "NOT_PERMITTED"
	ErrCodeConflict                 = "CONFLICT"
	ErrCodeAlreadySuccess           = "CONFLICT_SUCCESSED"
)

const (
	ErrTypeAPI            = "API_ERROR"
	ErrTypeInvalidRequest = "INVALID_REQUEST_ERROR"
	ErrTypeIdempotency    = "IDEMPOTENCY_ERROR"
	ErrTypePSP            = "PSP_ERROR"
	ErrTypeUnknown        = "UNKNOWN"
)
