// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_httpRequestExt

import (
	http "net/http"

	circuitbreaker "github.com/paper-indonesia/pdk/go/circuitbreaker"

	mock "github.com/stretchr/testify/mock"
)

// CBFallbackFn is an autogenerated mock type for the CBFallbackFn type
type CBFallbackFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CBFallbackFn) Execute(_a0 *http.Request) *circuitbreaker.CircuitBreakerResponse {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *circuitbreaker.CircuitBreakerResponse
	if rf, ok := ret.Get(0).(func(*http.Request) *circuitbreaker.CircuitBreakerResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*circuitbreaker.CircuitBreakerResponse)
		}
	}

	return r0
}

// NewCBFallbackFn creates a new instance of CBFallbackFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCBFallbackFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *CBFallbackFn {
	mock := &CBFallbackFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
