// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_httpRequestExt

import (
	httpRequestExt "github.com/paper-indonesia/pg-mcp-server/pkg/httpRequestExt"
	mock "github.com/stretchr/testify/mock"
)

// HTTPRequestConfig is an autogenerated mock type for the HTTPRequestConfig type
type HTTPRequestConfig struct {
	mock.Mock
}

// Execute provides a mock function with given fields: client
func (_m *HTTPRequestConfig) Execute(client *httpRequestExt.HTTPRequest) {
	_m.Called(client)
}

// NewHTTPRequestConfig creates a new instance of HTTPRequestConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPRequestConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPRequestConfig {
	mock := &HTTPRequestConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
