package constant

const (
	// 2xx
	SNAP_SUCCESS_CODE_PATTERN             = "^200..00$"
	SNAP_REQUEST_IN_PROGRESS_CODE_PATTERN = "^202..00$"

	// 4xx
	SNAP_BAD_REQUEST_CODE_PATTERN          = "^400..00$"
	SNAP_INVALID_FIELD_FORMAT_CODE_PATTERN = "^400..01$"
	SNAP_INVALID_MANDATORY_CODE_PATTERN    = "^400..02$"

	SNAP_UNAUTHORIZED_CODE_PATTERN             = "^401..00$"
	SNAP_INVALID_B2B_TOKEN_CODE_PATTERN        = "^401..01$"
	SNAP_INVALID_CUSTOMER_TOKEN_CODE_PATTERN   = "^401..02$"
	SNAP_TOKEN_NOT_FOUND_CODE_PATTERN          = "^401..03$"
	SNAP_CUSTOMER_TOKEN_NOT_FOUND_CODE_PATTERN = "^401..04$"

	SNAP_TRANSACTION_EXPIRED_CODE_PATTERN             = "^403..00$"
	SNAP_FEATURE_NOT_ALLOWED_CODE_PATTERN             = "^403..01$"
	SNAP_EXCEED_TRANSACTION_AMOUNT_LIMIT_CODE_PATTERN = "^403..02$"
	SNAP_SUSPECTED_FRAUD_CODE_PATTERN                 = "^403..03$"
	SNAP_ACTIVITY_COUNT_LIMIT_EXCEEDED_CODE_PATTERN   = "^403..04$"
	SNAP_DO_NOT_HONOR_CODE_PATTERN                    = "^403..05$"
	SNAP_FEATURE_NOT_ALLOWED_WITH_REASON_CODE_PATTERN = "^403..06$"
	SNAP_CARD_BLOCKER_CODE_PATTERN                    = "^403..07$"
	SNAP_CARD_EXPIRED_CODE_PATTERN                    = "^403..08$"
	SNAP_DORMANT_ACCOUNT_CODE_PATTERN                 = "^403..09$"
	SNAP_NEED_TO_SET_TOKEN_LIMIT_CODE_PATTERN         = "^403..10$"
	SNAP_OTP_BLOCKED_CODE_PATTERN                     = "^403..11$"
	SNAP_OTP_LIFETIME_EXPIRED_CODE_PATTERN            = "^403..12$"
	SNAP_OTP_SENT_TO_CARDHOLDER                       = "^403..13$"
	SNAP_INSUFFICIENT_FUNDS_CODE_PATTERN              = "^403..14$"
	SNAP_TRANSACTION_NOT_PERMITED_CODE_PATTERN        = "^403..15$" // Like transfer to forex account
	SNAP_SUSPEND_TRANSACTION_CODE_PATTERN             = "^403..16$"
	SNAP_TOKEN_LIMIT_EXCEEDED_CODE_PATTERN            = "^403..17$"
	SNAP_INACTIVE_ACCOUNT_CODE_PATTERN                = "^403..18$"
	SNAP_MERCHANT_BLACKLISTED_CODE_PATTERN            = "^403..19$"
	SNAP_MERCHANT_LIMIT_EXCEEDED_CODE_PATTERN         = "^403..20$"
	SNAP_SET_LIMIT_NOT_ALLOWED_CODE_PATTERN           = "^403..21$"
	SNAP_TOKEN_LIMIT_INVALID_CODE_PATTERN             = "^403..22$"
	SNAP_LIMIT_EXCEED_CODE_PATTERN                    = "^403..23$"

	SNAP_INVALID_TRANSACTION_STATUS_CODE_PATTERN   = "^404..00$"
	SNAP_TRANSACTION_NOT_FOUND_CODE_PATTERN        = "^404..01$"
	SNAP_INVALID_ROUTING_CODE_PATTERN              = "^404..02$"
	SNAP_BANK_NOT_SUPPORTED_BY_SWITCH_CODE_PATTERN = "^404..03$"
	SNAP_TRANSACTION_CANCELLED_CODE_PATTERN        = "^404..04$"
	SNAP_MERCHANT_NOT_REGISTERED_CODE_PATTERN      = "^404..05$"
	SNAP_NEED_TO_REQUEST_OTP_CODE_PATTERN          = "^404..06$"
	SNAP_JOURNEY_NOT_FOUND_CODE_PATTERN            = "^404..07$"
	SNAP_INVALID_MERCHANT_CODE_PATTERN             = "^404..08$"
	SNAP_INVALID_ACCOUNT_CODE_PATTERN              = "^404..11$"
	SNAP_INVALID_BILL_VA_WITH_REASON_CODE_PATTERN  = "^404..12$"
	SNAP_INVALID_AMOUNT_CODE_PATTERN               = "^404..13$"
	SNAP_PAID_BILL_CODE_PATTERN                    = "^404..14$"
	SNAP_PARTNER_NOT_FOUND_CODE_PATTERN            = "^404..16$"
	SNAP_INVALID_BILL_VA_CODE_PATTERN              = "^404..17$"
	SNAP_INVALID_VA_CODE_PATTERN                   = "^404..19$"

	SNAP_REQUEST_NOT_SUPPORTED_CODE_PATTERN         = "^405..00$"
	SNAP_REQUEST_OPERATION_NOT_ALLOWED_CODE_PATTERN = "^405..01$"

	SNAP_CONFLICT_CODE_PATTERN                       = "^409..00$"
	SNAP_DUPLICATE_PARTNER_REFERENCE_NO_CODE_PATTERN = "^409..01$"

	SNAP_TOO_MANY_REQUEST_CODE_PATTERN = "^429..00$"

	// 5xx
	SNAP_GENERAL_ERROR_CODE_PATTERN         = "^500..00$"
	SNAP_INTERNAL_SERVER_ERROR_CODE_PATTERN = "^500..01$"
	SNAP_EXTERNAL_SERVER_ERROR_CODE_PATTERN = "^500..02$"

	SNAP_TIMEOUT_CODE_PATTERN = "^504..00$"

	NUMERIC_REGEX = `^[0-9]+$`
)
